(()=>{
 const $=id=>document.getElementById(id),fmt=n=>Number(n||0).toLocaleString();let worker,manifest,current;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function network(){const on=navigator.onLine;$('connectionStatus').textContent=on?'Online':'Offline';$('connectionStatus').className='status-dot '+(on?'online':'offline');$('offlineNote').textContent=on?'Online • local dataset enabled':'Offline • serving IndexedDB dataset'}
 function ranks(id,items){const e=$(id);e.innerHTML='';const max=items[0]?.value||1;for(const x of items){const d=document.createElement('div');d.className='rank';d.innerHTML=`<span>${esc(x.label)}</span><strong>${fmt(x.value)}</strong><i><b style="width:${Math.max(2,x.value/max*100)}%"></b></i>`;e.appendChild(d)}}
 function timeline(items){const e=$('timeline');e.innerHTML='';const max=Math.max(1,...items.map(x=>x.value));for(const x of items){const b=document.createElement('span');b.className='bar';b.style.height=Math.max(2,x.value/max*100)+'%';b.title=`${x.year}: ${fmt(x.value)} voyages`;e.appendChild(b)}}
 function rows(items){$('voyageTable').innerHTML=items.map(r=>`<tr><td>${esc(r.voyageid)}</td><td>${esc(r.yearaf??r.yearam??r.yeardep??'—')}</td><td>${esc(r.majbyimp??r.mjbyptimp??'—')}</td><td>${esc(r.mjselimp1??r.mjselimp??'—')}</td><td>${fmt(r.tslavesd??r.slaximp)}</td><td>${fmt(r.slaarriv??r.slamimp)}</td><td>${esc(r.shipname??'—')}</td></tr>`).join('')}
 function query(){const f={from:$('yearFrom').value,to:$('yearTo').value,origin:$('origin').value,destination:$('destination').value,carrier:$('carrier').value,evidence:$('evidence').value};const u=new URL(location.href);for(const [k,v] of Object.entries(f))v?u.searchParams.set(k,v):u.searchParams.delete(k);history.replaceState({},'',u);return new Promise(resolve=>{const fn=e=>{if(e.data.type==='result'){worker.removeEventListener('message',fn);resolve(e.data.result)}};worker.addEventListener('message',fn);worker.postMessage({type:'query',filters:f})})}
 async function run(){current=await query();$('filteredCount').textContent=fmt(current.total);$('embarkedCount').textContent=fmt(current.embarked);$('disembarkedCount').textContent=fmt(current.disembarked);$('mortalityCount').textContent=current.averageMortalityRate==null?'—':current.averageMortalityRate.toFixed(2)+'%';timeline(current.years);ranks('origins',current.origins);ranks('destinations',current.destinations);ranks('carriers',current.carriers);rows(current.rows);$('resultCount').textContent=`${fmt(current.rows.length)} displayed locally`}
 function populate(id,vals){const s=$(id),seen=new Set();for(const v of vals||[]){if(v==null||seen.has(v))continue;seen.add(v);const o=document.createElement('option');o.value=v;o.textContent=v;s.appendChild(o)}}
 async function init(){network();addEventListener('online',network);addEventListener('offline',network);manifest=await SVAPI.manifest();$('snapshotDate').textContent=manifest.generated?new Date(manifest.generated).toLocaleString():'Local snapshot';$('snapshotStatus').textContent=manifest.status||'Static dataset';$('voyageCount').textContent=fmt(manifest.record_count);$('coverageYears').textContent=`${manifest.yearaf_min??'—'}–${manifest.yearaf_max??'—'}`;$('syncProgress').textContent='Loading local dataset…';const data=await SVAPI.loadVoyages({onProgress:p=>{$('syncProgress').textContent=p.stage==='download'?`Synchronizing ${p.current}/${p.total} chunks`:p.stage==='indexeddb'?`Using ${fmt(p.current)} local records`:'Initializing…'}});$('syncProgress').textContent=`${fmt(data.length)} records available offline`;populate('origin',data.map(r=>r.majbyimp??r.mjbyptimp));populate('destination',data.map(r=>r.mjselimp1??r.mjselimp));populate('carrier',data.map(r=>r.natinimp??r.national));for(const id of ['yearFrom','yearTo','origin','destination','carrier','evidence']){const v=new URLSearchParams(location.search).get(id);if(v!==null&&$(id))$(id).value=v}worker=SVAPI.worker(data);await new Promise(res=>worker.addEventListener('message',e=>e.data.type==='ready'&&res(),{once:true}));$('runQuery').onclick=run;$('resetFilters').onclick=()=>{['yearFrom','yearTo'].forEach((id,i)=>$(id).value=i?manifest.yearaf_max??1866:manifest.yearaf_min??1500);['origin','destination','carrier'].forEach(id=>$(id).value='');$('evidence').value='all';run()};$('shareQuery').onclick=()=>navigator.clipboard?.writeText(location.href);$('exportCSV').onclick=()=>{if(!current?.rows?.length)return;const cols=['voyageid','yearaf','yearam','yeardep','majbyimp','mjbyptimp','mjselimp','mjselimp1','tslavesd','slaximp','slaarriv','slamimp','shipname','natinimp','national'];const csv=[cols.join(','),...current.rows.map(r=>cols.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='slavevoyages-query.csv';a.click()};await run()}
 init().catch(e=>{$('syncProgress').textContent=e.message;console.error(e)});
})();
